import { Injectable } from '@nestjs/common';

export interface ApplicationEmailData {
  applicantName: string;
  applicantEmail: string;
  position: string;
  company: string;
  coverLetterContent?: string;
  applicationUrl?: string;
}

@Injectable()
export class EmailTemplateService {
  /**
   * Generate application email subject
   */
  generateApplicationSubject(data: ApplicationEmailData): string {
    return `Application for ${data.position} - ${data.applicantName}`;
  }

  /**
   * Generate application email body (HTML)
   */
  generateApplicationHtml(data: ApplicationEmailData): string {
    const coverLetterSection = data.coverLetterContent
      ? `
        <div style="margin-top: 24px; padding: 20px; background-color: #f9fafb; border-radius: 8px;">
          <h3 style="margin: 0 0 16px 0; font-size: 14px; color: #6b7280; text-transform: uppercase;">Cover Letter</h3>
          <div style="color: #374151; white-space: pre-wrap; font-size: 14px; line-height: 1.6;">
${this.escapeHtml(data.coverLetterContent)}
          </div>
        </div>
      `
      : '';

    return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Job Application</title>
</head>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; line-height: 1.6; color: #1f2937; max-width: 600px; margin: 0 auto; padding: 20px;">
  <div style="border-bottom: 2px solid #3b82f6; padding-bottom: 20px; margin-bottom: 24px;">
    <h1 style="margin: 0; font-size: 24px; color: #1f2937;">Job Application</h1>
    <p style="margin: 8px 0 0 0; color: #6b7280;">${data.position} at ${data.company}</p>
  </div>

  <div style="margin-bottom: 24px;">
    <p style="margin: 0 0 16px 0;">Dear Hiring Manager,</p>
    <p style="margin: 0 0 16px 0;">
      I am writing to express my strong interest in the <strong>${data.position}</strong> position at <strong>${data.company}</strong>.
    </p>
    <p style="margin: 0;">
      Please find my resume attached for your review. I believe my skills and experience make me a strong candidate for this role.
    </p>
  </div>

  ${coverLetterSection}

  <div style="margin-top: 32px; padding-top: 20px; border-top: 1px solid #e5e7eb;">
    <p style="margin: 0 0 8px 0;">Best regards,</p>
    <p style="margin: 0; font-weight: 600;">${data.applicantName}</p>
    <p style="margin: 4px 0 0 0; color: #6b7280; font-size: 14px;">${data.applicantEmail}</p>
  </div>

  <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; color: #9ca3af; font-size: 12px;">
    <p style="margin: 0;">
      This email was generated by TripaliumAI - Intelligent Job Application Platform
    </p>
  </div>
</body>
</html>
    `.trim();
  }

  /**
   * Generate application email body (Plain text)
   */
  generateApplicationText(data: ApplicationEmailData): string {
    const coverLetterSection = data.coverLetterContent
      ? `
---
COVER LETTER
---

${data.coverLetterContent}

`
      : '';

    return `
JOB APPLICATION
${data.position} at ${data.company}

Dear Hiring Manager,

I am writing to express my strong interest in the ${data.position} position at ${data.company}.

Please find my resume attached for your review. I believe my skills and experience make me a strong candidate for this role.

${coverLetterSection}
Best regards,
${data.applicantName}
${data.applicantEmail}

---
This email was generated by TripaliumAI - Intelligent Job Application Platform
    `.trim();
  }

  /**
   * Extract plain text from cover letter JSON content
   */
  extractCoverLetterText(content: unknown): string | undefined {
    if (!content) return undefined;

    try {
      const parsed = typeof content === 'string' ? JSON.parse(content) : content;

      // Handle structured cover letter format
      if (parsed.paragraphs && Array.isArray(parsed.paragraphs)) {
        return parsed.paragraphs.join('\n\n');
      }

      // Handle simple text format
      if (parsed.content && typeof parsed.content === 'string') {
        return parsed.content;
      }

      // Handle full body format
      if (parsed.body && typeof parsed.body === 'string') {
        return parsed.body;
      }

      // Fallback to stringifying
      if (typeof content === 'string') {
        return content;
      }

      return undefined;
    } catch {
      return typeof content === 'string' ? content : undefined;
    }
  }

  private escapeHtml(text: string): string {
    return text
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#039;');
  }
}
