#!/bin/bash
set -euo pipefail

# ============================================================================
# TripaliumAI Production Server Setup Script
# ============================================================================
# This script sets up a fresh production server for TripaliumAI.
# Run as root on the production VPS.
#
# Usage:
#   curl -sL https://raw.githubusercontent.com/OWNER/TripaliumAI/master/deploy/server-setup.sh | bash
#   OR
#   ./server-setup.sh
# ============================================================================

echo "========================================"
echo "  TripaliumAI Server Setup"
echo "========================================"
echo ""

# Check if running as root
if [[ $EUID -ne 0 ]]; then
   echo "Error: This script must be run as root"
   exit 1
fi

# Configuration
APP_DIR=/opt/tripalium
GITHUB_RAW_BASE="https://raw.githubusercontent.com"

# Detect if this is a fresh install or update
if [[ -d "$APP_DIR" ]]; then
    echo "Existing installation detected at $APP_DIR"
    echo "This script will update deployment files."
    read -p "Continue? [y/N] " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 0
    fi
fi

# Step 1: Install Docker if not present
echo ""
echo "[1/6] Checking Docker installation..."
if ! command -v docker &> /dev/null; then
    echo "Installing Docker..."
    curl -fsSL https://get.docker.com | sh
    systemctl enable docker
    systemctl start docker
    echo "Docker installed successfully"
else
    echo "Docker is already installed: $(docker --version)"
fi

# Step 2: Install Docker Compose plugin if not present
echo ""
echo "[2/6] Checking Docker Compose..."
if ! docker compose version &> /dev/null; then
    echo "Installing Docker Compose plugin..."
    apt-get update
    apt-get install -y docker-compose-plugin
    echo "Docker Compose installed successfully"
else
    echo "Docker Compose is available: $(docker compose version)"
fi

# Step 3: Create application directory
echo ""
echo "[3/6] Setting up application directory..."
mkdir -p "$APP_DIR"
cd "$APP_DIR"

# Step 4: Prompt for GitHub repository info
echo ""
echo "[4/6] GitHub Container Registry Setup"
echo ""
echo "To pull images from ghcr.io, you need a GitHub Personal Access Token"
echo "with 'read:packages' scope."
echo ""
echo "Create one at: https://github.com/settings/tokens/new"
echo "  - Select scope: read:packages"
echo ""
read -p "Enter your GitHub username: " GITHUB_USER
read -s -p "Enter your GitHub Personal Access Token: " GITHUB_TOKEN
echo ""

# Create Docker credential file
mkdir -p /root/.docker
echo "{\"auths\":{\"ghcr.io\":{\"auth\":\"$(echo -n "$GITHUB_USER:$GITHUB_TOKEN" | base64)\"}}}" > /root/.docker/config.json
chmod 600 /root/.docker/config.json

# Verify authentication
echo ""
echo "Testing registry authentication..."
if docker login ghcr.io -u "$GITHUB_USER" --password "$GITHUB_TOKEN" 2>/dev/null; then
    echo "Successfully authenticated with ghcr.io"
else
    echo "Warning: Could not verify authentication. Images may fail to pull."
fi

# Step 5: Download deployment files
echo ""
echo "[5/6] Downloading deployment files..."

# Ask for GitHub owner (for raw file downloads)
read -p "Enter the GitHub owner/org name for the repository: " GITHUB_OWNER

# Download files
echo "Downloading docker-compose.prod.yml..."
curl -sL "$GITHUB_RAW_BASE/$GITHUB_OWNER/TripaliumAI/master/docker-compose.prod.yml" -o docker-compose.yml

echo "Downloading Caddyfile..."
curl -sL "$GITHUB_RAW_BASE/$GITHUB_OWNER/TripaliumAI/master/Caddyfile" -o Caddyfile

echo "Downloading .env.template..."
curl -sL "$GITHUB_RAW_BASE/$GITHUB_OWNER/TripaliumAI/master/deploy/.env.template" -o .env.template

# Step 6: Create .env file if it doesn't exist
echo ""
echo "[6/6] Environment configuration..."
if [[ ! -f "$APP_DIR/.env" ]]; then
    # Generate secure random values
    POSTGRES_PW=$(openssl rand -base64 32 | tr -d '=' | head -c 32)
    JWT_SECRET=$(openssl rand -base64 32 | tr -d '=' | head -c 32)
    NEXTAUTH_SECRET=$(openssl rand -base64 32 | tr -d '=' | head -c 32)

    cat > "$APP_DIR/.env" << EOF
# Auto-generated by server-setup.sh
# Review and update values as needed

GITHUB_OWNER=${GITHUB_OWNER}

POSTGRES_USER=tripalium
POSTGRES_PASSWORD=${POSTGRES_PW}
POSTGRES_DB=tripalium

JWT_SECRET=${JWT_SECRET}
NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
NEXTAUTH_URL=https://tripalium.projets.work

OPENAI_API_KEY=sk-YOUR_KEY_HERE

SMTP_HOST=localhost
SMTP_PORT=1025
SMTP_FROM=noreply@tripalium.projets.work
ENABLE_REAL_EMAIL=false

CORS_ORIGINS=https://tripalium.projets.work
EOF

    chmod 600 "$APP_DIR/.env"
    echo "Created .env file with generated secrets"
    echo "IMPORTANT: Edit $APP_DIR/.env to add your OPENAI_API_KEY"
else
    echo ".env file already exists, preserving existing configuration"
    # Update GITHUB_OWNER if needed
    if ! grep -q "GITHUB_OWNER=" "$APP_DIR/.env"; then
        echo "GITHUB_OWNER=${GITHUB_OWNER}" >> "$APP_DIR/.env"
    fi
fi

# Summary
echo ""
echo "========================================"
echo "  Setup Complete!"
echo "========================================"
echo ""
echo "Application directory: $APP_DIR"
echo ""
echo "Files created:"
echo "  - docker-compose.yml (production config)"
echo "  - Caddyfile (reverse proxy config)"
echo "  - .env (environment variables)"
echo ""
echo "Next steps:"
echo ""
echo "  1. Edit the .env file to configure your secrets:"
echo "     nano $APP_DIR/.env"
echo ""
echo "  2. Start the services:"
echo "     cd $APP_DIR && docker compose up -d"
echo ""
echo "  3. View logs:"
echo "     docker compose logs -f"
echo ""
echo "  4. Watchtower will automatically update containers when"
echo "     new images are pushed to the registry."
echo ""
echo "For manual updates:"
echo "  cd $APP_DIR && docker compose pull && docker compose up -d"
echo ""
